- cmd/autobump/adapters.go
- cmd/autobump/changelog.go
- cmd/autobump/gitlab.go
- cmd/autobump/project.go
- configs/autobump.yaml
> feat(java): add support for Java and fixed package version update issues

- .github/PULL_REQUEST_TEMPLATE/bump.md
- .github/PULL_REQUEST_TEMPLATE/default.md
- cmd/autobump/config.go
- cmd/autobump/main.go
- cmd/autobump/project.go
Added config validation so the program will execute with an invalid config with invalid values and pointers.
Also added the PR templates from VersaInit.
> feat(config): added config validation

- README.md
- cmd/autobump/adapters.go
- cmd/autobump/config.go
- cmd/autobump/main.go
- cmd/autobump/project.go
- cmd/autobump/utils.go
- configs/autobump.yaml
> feat(RD-2291): added language detection and batch processing mode

- .github/workflows/release.yml
- cmd/autobump/config.go
- cmd/autobump/project.go
- configs/autobump.yaml
> feat(RD-2993): added CI token reading, auto cloning, and a release pipeline for use in the scheduled pipeline

- .github/workflows/release.yml
- Makefile
- cmd/autobump/main.go
> fix(config): fixed config finder conflicting with arg parser, corrected pipeline commands

- cmd/autobump/main.go
> fix(args): fixed config arg for batch subcommand

- cmd/autobump/project.go
> fix(gitlab): fixed GitLab CI job token authentication

- cmd/autobump/adapters.go
- cmd/autobump/config.go
- cmd/autobump/gitlab.go
- cmd/autobump/project.go
- configs/autobump.yaml
> feat(RD-2421): added the feature to load version files and patterns from config

- cmd/autobump/config.go
- cmd/autobump/git.go
> fix(https): fixed the issue of not using CI_JOB_TOKEN while pushing over HTTPS

- cmd/autobump/project.go
- cmd/autobump/utils.go
> fix(gpg-password): assume empty GPG key password when interactive terminal unavailable

- cmd/autobump/config.go
- cmd/autobump/gitlab.go
- cmd/autobump/main.go
- cmd/autobump/project.go
- cmd/autobump/versioning.go
- configs/autobump.yaml
> feat(token): added support for reading GitLab token from file

- cmd/autobump/git.go
- cmd/autobump/project.go
> feat(dco): added DCO sign-off to commit messages

- cmd/autobump/project.go
> fix(file): fixed an error the wrong version file path is checked

- cmd/autobump/changelog.go
- cmd/autobump/config.go
- cmd/autobump/project.go
- cmd/autobump/utils.go
- cmd/autobump/versioning.go
- configs/autobump.yaml
> feat(changelog): fixed CHANGELOG.md key section orders; added support for per-file version patterns

- cmd/autobump/changelog.go
> fix(version): fixed the errors in incrementing the version numbers

- cmd/autobump/changelog.go
- cmd/autobump/config.go
- cmd/autobump/project.go
- cmd/autobump/versioning.go
- configs/autobump.yaml
- Some changes are made by the new formatter `golines` which I've incorporated to automatically wrap the long lines.
- `languages.[n].pattern` has been changed from a str to a list `languages.[n].patterns` so one version file can have multiple patterns.
> feat(RD-2540): added support for C# and JavaScript/TypeScript

- cmd/autobump/changelog.go
- cmd/autobump/project.go
> feat(RD-2527): added the feature to avoid empty bumps

- cmd/autobump/changelog.go
> fix(changelog): fixed changelog patch number calculations

- CHANGELOG.md
- cmd/autobump/changelog.go
> feat(RD-2927): made changelog processing adhere to keep a changelog version 1.1.0 standard

- CHANGELOG.md
- go.mod
- go.sum
> fix(dependencies): downgraded `go-git` to v5.9.0 to fix the pipeline

- CHANGELOG.md
- Makefile
- cmd/autobump/git.go
- cmd/autobump/main.go
- cmd/autobump/project.go
> feat(git): try all authentication methods

- .editorconfig
- CHANGELOG.md
- cmd/autobump/git.go
- cmd/autobump/project.go
> fix(project): fixed project processing and cloning logic

- CHANGELOG.md
- cmd/autobump/azuredevops.go
- cmd/autobump/changelog.go
- cmd/autobump/config.go
- cmd/autobump/git.go
- cmd/autobump/gitlab.go
- cmd/autobump/language.go
- cmd/autobump/main.go
- cmd/autobump/project.go
- cmd/autobump/python.go
- cmd/autobump/utils.go
- cmd/autobump/versioning.go
- go.mod
- go.sum
> feat(versioning): added the feature to read project names from language config

- CHANGELOG.md
- cmd/autobump/versioning.go
> fix(project): fixed project name `-` to `_` replacement

- CHANGELOG.md
- cmd/autobump/changelog.go
> feat(changelog): increment the version number only by one

- CHANGELOG.md
- cmd/autobump/changelog.go
> fix(changelog): added missing CHANGELOG.md sections

- CHANGELOG.md
> chore(bump): bumped version to 2.13.0

- CHANGELOG.md
- cmd/autobump/changelog.go
> feat(changelog): added the feature to automatically fix incorrect section heading levels

- CHANGELOG.md
- cmd/autobump/project.go
> fix(project): fixed a null pointer dereference when opening repositories
